import "./globals.css";

import { Bruno_Ace } from "next/font/google";
import type { Metadata } from "next";

const brunoAce = Bruno_Ace({
  variable: "--font-bruno-ace",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${brunoAce.variable} antialiased`}>{children}</body>
    </html>
  );
}
